# Generated by Django 2.2 on 2020-01-14 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollmentNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('course', models.CharField(max_length=2000)),
                ('year', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagUID', models.CharField(max_length=200)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentAttendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TapTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tapAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentAttendance.Tag')),
            ],
        ),
    ]
